[package]
name = "kafka-driver-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Deterministic simulation support for kafka-driver"
publish = false

[dependencies]
criticality.workspace = true
kafka-driver-core.workspace = true

[lints]
workspace = true
