//! Canonical dependency, generated-provenance, and tightening-ratchet state.

mod canonical;

use std::{error::Error, fmt, fs, path::Path};

use serde::{Deserialize, Serialize};

use crate::input::{read_text, replace_text};

pub const LOCK_SCHEMA: u64 = 2;
pub const LOCK_SEMANTICS: u64 = 1;

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockFile {
    pub schema: u64,
    #[serde(default = "default_semantics")]
    pub semantics: u64,
    #[serde(alias = "engine")]
    pub producer: String,
    pub contract_sha256: String,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
    #[serde(default, rename = "generated", skip_serializing_if = "Vec::is_empty")]
    pub generated: Vec<LockedGeneratedSource>,
    #[serde(default, rename = "gate", skip_serializing_if = "Vec::is_empty")]
    pub gates: Vec<LockedGate>,
    #[serde(default, rename = "ratchet")]
    pub ratchets: Vec<LockedRatchet>,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedGeneratedSource {
    pub root: String,
    pub manifest_sha256: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedGate {
    pub name: String,
    pub path: String,
    pub sha256: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedPackage {
    pub name: String,
    #[serde(default, rename = "dependency")]
    pub dependencies: Vec<LockedDependency>,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedDependency {
    pub name: String,
    pub kind: LockedDependencyKind,
    pub scope: LockedDependencyScope,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LockedDependencyKind {
    Normal,
    Development,
    Build,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LockedDependencyScope {
    Internal,
    External,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedRatchet {
    pub rule: String,
    pub target: String,
    pub value: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LockError(String);

impl fmt::Display for LockError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for LockError {}

impl LockFile {
    pub fn new(contract_sha256: impl Into<String>) -> Self {
        Self {
            schema: LOCK_SCHEMA,
            semantics: LOCK_SEMANTICS,
            producer: env!("CARGO_PKG_VERSION").into(),
            contract_sha256: contract_sha256.into(),
            packages: Vec::new(),
            generated: Vec::new(),
            gates: Vec::new(),
            ratchets: Vec::new(),
        }
    }

    pub fn read(path: &Path) -> Result<Self, LockError> {
        let source = read_text(path).map_err(LockError)?;
        let mut lock = toml::from_str::<Self>(&source)
            .map_err(|error| LockError(format!("parse {}: {error}", path.display())))?;
        lock.canonicalize()?;
        let canonical = source == lock.render()?;
        let legacy = lock.schema == 1 && source == lock.render_legacy()?;
        if !canonical && !legacy {
            return Err(LockError(format!(
                "{} is not canonical; run `zrail update`",
                path.display()
            )));
        }
        Ok(lock)
    }

    pub fn read_optional(path: &Path) -> Result<Option<Self>, LockError> {
        match fs::symlink_metadata(path) {
            Ok(_) => Self::read(path).map(Some),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(LockError(format!(
                "inspect optional lock {}: {error}",
                path.display()
            ))),
        }
    }

    pub fn render(&self) -> Result<String, LockError> {
        let mut lock = self.clone();
        lock.canonicalize()?;
        let body = toml::to_string_pretty(&lock)
            .map_err(|error| LockError(format!("serialize zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }

    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        replace_text(path, &self.render()?).map_err(LockError)
    }

    pub fn has_current_semantics(&self) -> bool {
        self.semantics == LOCK_SEMANTICS
    }

    pub fn same_resolved_state(&self, other: &Self) -> bool {
        self.semantics == other.semantics
            && self.contract_sha256 == other.contract_sha256
            && self.packages == other.packages
            && self.generated == other.generated
            && self.gates == other.gates
            && self.ratchets == other.ratchets
    }

    fn render_legacy(&self) -> Result<String, LockError> {
        let legacy = LegacyLockFile {
            schema: self.schema,
            engine: &self.producer,
            contract_sha256: &self.contract_sha256,
            packages: &self.packages,
            generated: &self.generated,
            gates: &self.gates,
            ratchets: &self.ratchets,
        };
        let body = toml::to_string_pretty(&legacy)
            .map_err(|error| LockError(format!("serialize legacy zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }
}

const fn default_semantics() -> u64 {
    1
}

#[derive(Serialize)]
struct LegacyLockFile<'a> {
    schema: u64,
    engine: &'a str,
    contract_sha256: &'a str,
    #[serde(rename = "package")]
    packages: &'a Vec<LockedPackage>,
    #[serde(rename = "generated", skip_serializing_if = "Vec::is_empty")]
    generated: &'a Vec<LockedGeneratedSource>,
    #[serde(rename = "gate", skip_serializing_if = "Vec::is_empty")]
    gates: &'a Vec<LockedGate>,
    #[serde(rename = "ratchet")]
    ratchets: &'a Vec<LockedRatchet>,
}

#[cfg(test)]
#[path = "lock_test.rs"]
mod lock_test;
