//! Canonical dependency, generated-provenance, and tightening-ratchet state.

mod canonical;

use std::{error::Error, fmt, path::Path};

use serde::{Deserialize, Serialize};

use crate::input::{read_text, replace_text};

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockFile {
    pub schema: u64,
    pub engine: String,
    pub contract_sha256: String,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
    #[serde(default, rename = "generated", skip_serializing_if = "Vec::is_empty")]
    pub generated: Vec<LockedGeneratedSource>,
    #[serde(default, rename = "gate", skip_serializing_if = "Vec::is_empty")]
    pub gates: Vec<LockedGate>,
    #[serde(default, rename = "ratchet")]
    pub ratchets: Vec<LockedRatchet>,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedGeneratedSource {
    pub root: String,
    pub manifest_sha256: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedGate {
    pub name: String,
    pub path: String,
    pub sha256: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedPackage {
    pub name: String,
    #[serde(default, rename = "dependency")]
    pub dependencies: Vec<LockedDependency>,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedDependency {
    pub name: String,
    pub kind: LockedDependencyKind,
    pub scope: LockedDependencyScope,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LockedDependencyKind {
    Normal,
    Development,
    Build,
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum LockedDependencyScope {
    Internal,
    External,
}

#[derive(Clone, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedRatchet {
    pub rule: String,
    pub target: String,
    pub value: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LockError(String);

impl fmt::Display for LockError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for LockError {}

impl LockFile {
    pub fn new(contract_sha256: impl Into<String>) -> Self {
        Self {
            schema: 1,
            engine: env!("CARGO_PKG_VERSION").into(),
            contract_sha256: contract_sha256.into(),
            packages: Vec::new(),
            generated: Vec::new(),
            gates: Vec::new(),
            ratchets: Vec::new(),
        }
    }

    pub fn read(path: &Path) -> Result<Self, LockError> {
        let source = read_text(path).map_err(LockError)?;
        let mut lock = toml::from_str::<Self>(&source)
            .map_err(|error| LockError(format!("parse {}: {error}", path.display())))?;
        lock.canonicalize()?;
        if source != lock.render()? {
            return Err(LockError(format!(
                "{} is not canonical; run `zrail update`",
                path.display()
            )));
        }
        Ok(lock)
    }

    pub fn render(&self) -> Result<String, LockError> {
        let mut lock = self.clone();
        lock.canonicalize()?;
        let body = toml::to_string_pretty(&lock)
            .map_err(|error| LockError(format!("serialize zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }

    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        replace_text(path, &self.render()?).map_err(LockError)
    }
}

#[cfg(test)]
#[path = "lock_test.rs"]
mod lock_test;
