//! Lock epochs retain explicit legacy reads without conflating current formats.

use std::{fs, path::PathBuf};

use super::super::{
    LockFile, LockedDependency, LockedDependencyKind, LockedDependencyScope,
    LockedDependencySource, LockedPackage,
};

#[test]
fn schema_two_legacy_dependency_shape_remains_readable() {
    let root = fixture_root("schema-two-legacy");
    reset(&root);
    let path = root.join("zrail.lock");
    fs::write(
        &path,
        concat!(
            "# This file is generated by `zrail update`; do not edit by hand.\n",
            "schema = 2\n",
            "semantics = 1\n",
            "producer = \"0.0.1\"\n",
            "contract_sha256 = \"00000000000000000000000000000000",
            "00000000000000000000000000000000\"\n",
            "ratchet = []\n\n",
            "[[package]]\n",
            "name = \"app\"\n\n",
            "[[package.dependency]]\n",
            "name = \"core\"\n",
            "kind = \"normal\"\n",
            "scope = \"internal\"\n",
        ),
    )
    .expect("write legacy schema-two lock");

    let read = LockFile::read(&path).expect("read legacy schema-two lock");

    assert_eq!(read.schema, 2);
    assert_eq!(read.semantics, 1);
    assert_eq!(read.packages[0].dependencies[0].alias, None);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_two_source_aware_locks_remain_readable() {
    let root = fixture_root("schema-two");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 2;
    lock.semantics = 2;
    lock.producer = "0.0.1".into();
    lock.packages.push(LockedPackage {
        name: "app".into(),
        dependencies: vec![LockedDependency {
            alias: Some("serde".into()),
            name: "serde".into(),
            crate_root: None,
            kind: LockedDependencyKind::Normal,
            scope: LockedDependencyScope::External,
            target: None,
            optional: Some(false),
            default_features: Some(true),
            features: vec!["derive".into()],
            source: Some(LockedDependencySource::Registry {
                registry: None,
                index: None,
                requirement: "1".into(),
            }),
        }],
    });
    lock.write(&path).expect("write schema-two lock");

    let read = LockFile::read(&path).expect("read schema-two lock");

    assert_eq!(read.schema, 2);
    assert_eq!(read.semantics, 2);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_three_alias_aware_locks_remain_readable() {
    let root = fixture_root("schema-three");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 3;
    lock.semantics = 3;
    lock.producer = "0.0.1".into();
    lock.packages.push(LockedPackage {
        name: "app".into(),
        dependencies: vec![LockedDependency {
            alias: Some("serde".into()),
            name: "serde".into(),
            crate_root: None,
            kind: LockedDependencyKind::Normal,
            scope: LockedDependencyScope::External,
            target: None,
            optional: Some(false),
            default_features: Some(true),
            features: Vec::new(),
            source: Some(LockedDependencySource::Registry {
                registry: None,
                index: None,
                requirement: "1".into(),
            }),
        }],
    });
    lock.write(&path).expect("write schema-three lock");

    let read = LockFile::read(&path).expect("read schema-three lock");

    assert_eq!(read.schema, 3);
    assert_eq!(read.semantics, 3);
    assert_eq!(read.packages[0].dependencies[0].crate_root, None);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn semantic_epoch_four_requires_schema_four() {
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 3;

    let error = lock
        .render()
        .expect_err("old schema must not claim new semantics");

    assert!(error.to_string().contains("require lock schema 4"));
}

fn fixture_root(name: &str) -> PathBuf {
    std::env::temp_dir().join(format!("zrail-lock-{name}-{}", std::process::id()))
}

fn reset(root: &PathBuf) {
    if root.exists() {
        fs::remove_dir_all(root).expect("reset fixture");
    }
    fs::create_dir_all(root).expect("create fixture");
}
