//! Lock epochs retain explicit legacy reads without conflating current formats.

use std::{fs, path::PathBuf};

use super::super::{
    LockFile, LockedDependency, LockedDependencyKind, LockedDependencyScope,
    LockedDependencySource, LockedGate, LockedMacroDefinition, LockedPackage,
};

#[test]
fn schema_two_legacy_dependency_shape_remains_readable() {
    let root = fixture_root("schema-two-legacy");
    reset(&root);
    let path = root.join("zrail.lock");
    fs::write(
        &path,
        concat!(
            "# This file is generated by `zrail update`; do not edit by hand.\n",
            "schema = 2\n",
            "semantics = 1\n",
            "producer = \"0.0.1\"\n",
            "contract_sha256 = \"00000000000000000000000000000000",
            "00000000000000000000000000000000\"\n",
            "ratchet = []\n\n",
            "[[package]]\n",
            "name = \"app\"\n\n",
            "[[package.dependency]]\n",
            "name = \"core\"\n",
            "kind = \"normal\"\n",
            "scope = \"internal\"\n",
        ),
    )
    .expect("write legacy schema-two lock");

    let read = LockFile::read(&path).expect("read legacy schema-two lock");

    assert_eq!(read.schema, 2);
    assert_eq!(read.semantics, 1);
    assert_eq!(read.packages[0].dependencies[0].alias, None);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_two_source_aware_locks_remain_readable() {
    let root = fixture_root("schema-two");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 2;
    lock.semantics = 2;
    lock.producer = "0.0.1".into();
    lock.packages.push(LockedPackage {
        name: "app".into(),
        dependencies: vec![LockedDependency {
            alias: Some("serde".into()),
            name: "serde".into(),
            crate_root: None,
            kind: LockedDependencyKind::Normal,
            scope: LockedDependencyScope::External,
            target: None,
            optional: Some(false),
            default_features: Some(true),
            features: vec!["derive".into()],
            source: Some(LockedDependencySource::Registry {
                registry: None,
                index: None,
                requirement: "1".into(),
            }),
        }],
    });
    lock.write(&path).expect("write schema-two lock");

    let read = LockFile::read(&path).expect("read schema-two lock");

    assert_eq!(read.schema, 2);
    assert_eq!(read.semantics, 2);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_three_alias_aware_locks_remain_readable() {
    let root = fixture_root("schema-three");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 3;
    lock.semantics = 3;
    lock.producer = "0.0.1".into();
    lock.packages.push(LockedPackage {
        name: "app".into(),
        dependencies: vec![LockedDependency {
            alias: Some("serde".into()),
            name: "serde".into(),
            crate_root: None,
            kind: LockedDependencyKind::Normal,
            scope: LockedDependencyScope::External,
            target: None,
            optional: Some(false),
            default_features: Some(true),
            features: Vec::new(),
            source: Some(LockedDependencySource::Registry {
                registry: None,
                index: None,
                requirement: "1".into(),
            }),
        }],
    });
    lock.write(&path).expect("write schema-three lock");

    let read = LockFile::read(&path).expect("read schema-three lock");

    assert_eq!(read.schema, 3);
    assert_eq!(read.semantics, 3);
    assert_eq!(read.packages[0].dependencies[0].crate_root, None);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_five_definition_locks_remain_readable() {
    let root = fixture_root("schema-five");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 5;
    lock.semantics = 5;
    lock.producer = "0.0.1".into();
    lock.macros.push(LockedMacroDefinition {
        path: "src/lib.rs".into(),
        name: "local::reviewed".into(),
        ordinal: 1,
        sha256: "1".repeat(64),
    });
    lock.write(&path).expect("write schema-five lock");

    let read = LockFile::read(&path).expect("read schema-five lock");

    assert_eq!(read.schema, 5);
    assert_eq!(read.macros.len(), 1);
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn schema_six_gate_locks_remain_readable_without_behavioral_inputs() {
    let root = fixture_root("schema-six");
    reset(&root);
    let path = root.join("zrail.lock");
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 6;
    lock.semantics = 6;
    lock.producer = "0.0.1".into();
    lock.gates.push(LockedGate {
        name: "check".into(),
        path: "scripts/check".into(),
        sha256: "1".repeat(64),
        inputs: Vec::new(),
    });
    lock.write(&path).expect("write schema-six lock");

    let read = LockFile::read(&path).expect("read schema-six lock");

    assert_eq!(read.schema, 6);
    assert!(read.gates[0].inputs.is_empty());
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn semantic_epoch_four_requires_schema_four() {
    let mut lock = LockFile::new("0".repeat(64));
    lock.schema = 3;

    let error = lock
        .render()
        .expect_err("old schema must not claim new semantics");

    assert!(error.to_string().contains("require lock schema 4"));
}

#[test]
fn semantic_epoch_five_requires_schema_five() {
    let error = super::validate_epochs(4, 5).expect_err("schema four cannot encode macro state");
    assert!(error.to_string().contains("require lock schema 5"));
    super::validate_epochs(5, 5).expect("legacy epochs are compatible");
}

#[test]
fn semantic_epoch_six_requires_schema_six() {
    let error = super::validate_epochs(5, 6).expect_err("schema five cannot encode manifests");
    assert!(error.to_string().contains("require lock schema 6"));
    super::validate_epochs(6, 6).expect("current epochs are compatible");
}

#[test]
fn semantic_epoch_seven_requires_schema_seven() {
    let error = super::validate_epochs(6, 7).expect_err("schema six cannot encode gate inputs");
    assert!(error.to_string().contains("require lock schema 7"));
    super::validate_epochs(7, 7).expect("current epochs are compatible");
}

fn fixture_root(name: &str) -> PathBuf {
    std::env::temp_dir().join(format!("zrail-lock-{name}-{}", std::process::id()))
}

fn reset(root: &PathBuf) {
    if root.exists() {
        fs::remove_dir_all(root).expect("reset fixture");
    }
    fs::create_dir_all(root).expect("create fixture");
}
