//! Canonical lock serialization and filesystem access.

use std::{fs, path::Path};

use serde::Serialize;

use crate::input::{read_text, replace_text};

use super::{
    LockError, LockFile, LockedGate, LockedGeneratedSource, LockedMacroDefinition,
    LockedMacroImplementation, LockedPackage, LockedRatchet,
};

impl LockFile {
    pub fn read(path: &Path) -> Result<Self, LockError> {
        let source = read_text(path).map_err(LockError)?;
        let mut lock = toml::from_str::<Self>(&source)
            .map_err(|error| LockError(format!("parse {}: {error}", path.display())))?;
        lock.canonicalize()?;
        let canonical = source == lock.render()?;
        let legacy = lock.schema == 1 && source == lock.render_legacy()?;
        if !canonical && !legacy {
            return Err(LockError(format!(
                "{} is not canonical; run `zrail update`",
                path.display()
            )));
        }
        Ok(lock)
    }

    pub fn read_optional(path: &Path) -> Result<Option<Self>, LockError> {
        match fs::symlink_metadata(path) {
            Ok(_) => Self::read(path).map(Some),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(LockError(format!(
                "inspect optional lock {}: {error}",
                path.display()
            ))),
        }
    }

    pub fn render(&self) -> Result<String, LockError> {
        let mut lock = self.clone();
        lock.canonicalize()?;
        let body = toml::to_string_pretty(&lock)
            .map_err(|error| LockError(format!("serialize zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }

    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        replace_text(path, &self.render()?).map_err(LockError)
    }

    fn render_legacy(&self) -> Result<String, LockError> {
        let legacy = LegacyLockFile {
            schema: self.schema,
            engine: &self.producer,
            contract_sha256: &self.contract_sha256,
            packages: &self.packages,
            generated: &self.generated,
            gates: &self.gates,
            macros: &self.macros,
            macro_implementations: &self.macro_implementations,
            ratchets: &self.ratchets,
        };
        let body = toml::to_string_pretty(&legacy)
            .map_err(|error| LockError(format!("serialize legacy zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }
}

#[derive(Serialize)]
struct LegacyLockFile<'a> {
    schema: u64,
    engine: &'a str,
    contract_sha256: &'a str,
    #[serde(rename = "package")]
    packages: &'a Vec<LockedPackage>,
    #[serde(rename = "generated", skip_serializing_if = "Vec::is_empty")]
    generated: &'a Vec<LockedGeneratedSource>,
    #[serde(rename = "gate", skip_serializing_if = "Vec::is_empty")]
    gates: &'a Vec<LockedGate>,
    #[serde(rename = "macro", skip_serializing_if = "Vec::is_empty")]
    macros: &'a Vec<LockedMacroDefinition>,
    #[serde(rename = "macro_implementation", skip_serializing_if = "Vec::is_empty")]
    macro_implementations: &'a Vec<LockedMacroImplementation>,
    #[serde(rename = "ratchet")]
    ratchets: &'a Vec<LockedRatchet>,
}
