//! Canonical lock serialization and filesystem access.

use std::{fs, path::Path};

use crate::input::{read_text, replace_text};

use super::{LockError, LockFile};

impl LockFile {
    /// Reads, validates, and canonicalizes an existing lock file.
    ///
    /// The path must be a bounded UTF-8 regular file, not a symlink. Parsing
    /// rejects unknown TOML fields, validation rejects incomplete state, and
    /// the original bytes must exactly equal [`Self::render`] or an error asks
    /// the caller to run `zrail update`.
    pub fn read(path: &Path) -> Result<Self, LockError> {
        let source = read_text(path).map_err(LockError)?;
        let mut lock = toml::from_str::<Self>(&source)
            .map_err(|error| LockError(format!("parse {}: {error}", path.display())))?;
        lock.canonicalize()?;
        let canonical = source == lock.render()?;
        if !canonical {
            return Err(LockError(format!(
                "{} is not canonical; run `zrail update`",
                path.display()
            )));
        }
        Ok(lock)
    }

    /// Reads a lock when present, returning `None` only for true absence.
    ///
    /// Dangling symlinks, directories, permission failures, invalid content,
    /// and every inspection error other than `NotFound` return [`LockError`].
    pub fn read_optional(path: &Path) -> Result<Option<Self>, LockError> {
        match fs::symlink_metadata(path) {
            Ok(_) => Self::read(path).map(Some),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(LockError(format!(
                "inspect optional lock {}: {error}",
                path.display()
            ))),
        }
    }

    /// Returns canonical generated-file text without mutating this lock.
    ///
    /// A clone is validated and ordered before pretty TOML serialization. The
    /// result starts with the generated-file warning and ends with a newline.
    pub fn render(&self) -> Result<String, LockError> {
        let mut lock = self.clone();
        lock.canonicalize()?;
        let mut body = toml::to_string_pretty(&lock)
            .map_err(|error| LockError(format!("serialize zrail.lock: {error}")))?;
        // Released epochs retain exact canonical bytes for migration review. Rename
        // only the table key, never similarly spelled text inside a string value.
        if lock.semantics <= 4 {
            let mut document = body
                .parse::<toml_edit::DocumentMut>()
                .map_err(|error| LockError(format!("render legacy macro digest: {error}")))?;
            if let Some(tables) = document
                .get_mut("macro_implementation")
                .and_then(toml_edit::Item::as_array_of_tables_mut)
            {
                for table in tables.iter_mut() {
                    if let Some(digest) = table.remove("inputs_sha256") {
                        table.insert("manifest_sha256", digest);
                    }
                }
            }
            body = document.to_string();
        }
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }

    /// Canonically renders and safely replaces or creates `path`.
    ///
    /// Rendering failures perform no write. Replacement uses a synced temporary
    /// file and refuses existing symlinks or non-regular destinations.
    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        replace_text(path, &self.render()?).map_err(LockError)
    }
}
