//! Canonical lock serialization and filesystem access.

use std::{fs, path::Path};

use crate::input::{read_text, replace_text};

use super::{LockError, LockFile};

impl LockFile {
    pub fn read(path: &Path) -> Result<Self, LockError> {
        let source = read_text(path).map_err(LockError)?;
        let mut lock = toml::from_str::<Self>(&source)
            .map_err(|error| LockError(format!("parse {}: {error}", path.display())))?;
        lock.canonicalize()?;
        let canonical = source == lock.render()?;
        if !canonical {
            return Err(LockError(format!(
                "{} is not canonical; run `zrail update`",
                path.display()
            )));
        }
        Ok(lock)
    }

    pub fn read_optional(path: &Path) -> Result<Option<Self>, LockError> {
        match fs::symlink_metadata(path) {
            Ok(_) => Self::read(path).map(Some),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(LockError(format!(
                "inspect optional lock {}: {error}",
                path.display()
            ))),
        }
    }

    pub fn render(&self) -> Result<String, LockError> {
        let mut lock = self.clone();
        lock.canonicalize()?;
        let body = toml::to_string_pretty(&lock)
            .map_err(|error| LockError(format!("serialize zrail.lock: {error}")))?;
        Ok(format!(
            "# This file is generated by `zrail update`; do not edit by hand.\n{body}"
        ))
    }

    pub fn write(&self, path: &Path) -> Result<(), LockError> {
        replace_text(path, &self.render()?).map_err(LockError)
    }
}
