#!/usr/bin/env bash
set -euo pipefail

cargo fmt --package kafka-driver --package kafka-driver-core --package kafka-driver-probe --package kafka-driver-sim --package kafka-driver-transport -- --check
cargo clippy --locked --workspace --all-targets --all-features -- -D warnings
cargo clippy --locked --workspace --all-targets --no-default-features -- -D warnings
cargo test --locked --workspace --all-features
RUSTDOCFLAGS="-D warnings" cargo doc --locked --workspace --all-features --no-deps
git diff --check
git diff --exit-code
