//! Provenance manifests reject edited, smuggled, and nonportable generated source.

use std::{fs, path::PathBuf};

use zrail_core::GeneratedSourceContract;

use crate::inventory::{RepositoryEntry, RepositoryEntryKind};

use super::{digest, inspect_tree, manifest};

const SCHEMA: &str = "message Message {}\n";

#[test]
fn exact_generated_tree_passes() {
    let root = fixture_root("valid");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("generated/message.rs"), source).expect("write source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        manifest(&[("message.rs", source)]),
    )
    .expect("write manifest");

    let findings = inspect_tree(&root, &entries(&root, &["message.rs"]), &contract());

    assert!(findings.is_empty(), "{findings:?}");
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn edited_and_smuggled_generated_source_fails() {
    let root = fixture_root("tampered");
    reset(&root);
    let original = "//! @generated by fixture\npub struct Message;\n";
    fs::write(
        root.join("generated/message.rs"),
        "//! @generated by fixture\npub struct Edited;\n",
    )
    .expect("write edited source");
    fs::write(
        root.join("generated/smuggled.rs"),
        "//! @generated by fixture\npub struct Smuggled;\n",
    )
    .expect("write smuggled source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        manifest(&[("message.rs", original)]),
    )
    .expect("write manifest");

    let findings = inspect_tree(
        &root,
        &entries(&root, &["message.rs", "smuggled.rs"]),
        &contract(),
    );

    assert!(findings.iter().any(|finding| finding.id == "GEN-002"));
    assert!(findings.iter().any(|finding| finding.id == "GEN-003"));
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn case_variant_source_extensions_cannot_escape_the_manifest() {
    let root = fixture_root("case-variant");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("generated/message.RS"), source).expect("write source");
    fs::write(root.join("generated/MANIFEST.json"), manifest(&[])).expect("write manifest");

    let findings = inspect_tree(&root, &entries(&root, &["message.RS"]), &contract());

    assert!(findings.iter().any(|finding| finding.id == "GEN-003"));
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn manifest_paths_are_normalized_and_source_only() {
    assert!(manifest::file_path("generated", "../escape.rs").is_err());
    assert!(manifest::file_path("generated", "nested\\escape.rs").is_err());
    assert!(manifest::file_path("generated", "artifact.bin").is_err());
    assert_eq!(
        manifest::file_path("generated", "nested/message.rs").as_deref(),
        Ok("generated/nested/message.rs")
    );
}

#[test]
fn edited_generator_input_fails() {
    let root = fixture_root("edited-input");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("schema/protocol.schema"), "message Edited {}\n").expect("edit schema");
    fs::write(root.join("generated/message.rs"), source).expect("write source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        manifest(&[("message.rs", source)]),
    )
    .expect("write manifest");

    let findings = inspect_tree(&root, &entries(&root, &["message.rs"]), &contract());

    assert!(findings.iter().any(|finding| finding.id == "GEN-004"));
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn missing_input_selectors_fail_closed() {
    let root = fixture_root("missing-input-selectors");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("generated/message.rs"), source).expect("write source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        manifest(&[("message.rs", source)]),
    )
    .expect("write manifest");
    let mut legacy = contract();
    legacy.inputs.clear();

    let findings = inspect_tree(&root, &entries(&root, &["message.rs"]), &legacy);

    assert!(findings.iter().any(|finding| {
        finding.id == "GEN-005" && finding.message.contains("outside the declared selectors")
    }));
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn missing_manifest_input_census_fails_closed() {
    let root = fixture_root("missing-manifest-inputs");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("generated/message.rs"), source).expect("write source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        format!(
            "{{\"schema\":1,\"generator\":\"fixture 1\",\"files\":[{{\"path\":\"message.rs\",\"sha256\":\"{}\"}}]}}",
            digest(source)
        ),
    )
    .expect("write legacy manifest");

    let findings = inspect_tree(&root, &entries(&root, &["message.rs"]), &contract());

    assert!(findings.iter().any(|finding| finding.id == "GEN-001"));
    fs::remove_dir_all(root).expect("remove fixture");
}

#[test]
fn smuggled_input_and_stale_selector_fail() {
    let root = fixture_root("input-census");
    reset(&root);
    let source = "//! @generated by fixture\npub struct Message;\n";
    fs::write(root.join("schema/extra.schema"), "message Extra {}\n").expect("write extra");
    fs::write(root.join("generated/message.rs"), source).expect("write source");
    fs::write(
        root.join("generated/MANIFEST.json"),
        manifest(&[("message.rs", source)]),
    )
    .expect("write manifest");
    let mut repository_entries = entries(&root, &["message.rs"]);
    repository_entries.push(entry(&root, "schema/extra.schema"));

    let findings = inspect_tree(&root, &repository_entries, &contract());
    let mut stale = contract();
    stale.inputs = vec!["missing/**".into()];
    let stale_findings = inspect_tree(&root, &repository_entries, &stale);
    let mut self_attesting = contract();
    self_attesting.inputs = vec!["generated/**".into()];
    let self_findings = inspect_tree(&root, &repository_entries, &self_attesting);

    assert!(findings.iter().any(|finding| finding.id == "GEN-005"));
    assert!(stale_findings.iter().any(|finding| finding.id == "GEN-005"));
    assert!(self_findings.iter().any(|finding| {
        finding.id == "GEN-005" && finding.message.contains("cannot attest itself")
    }));
    fs::remove_dir_all(root).expect("remove fixture");
}

fn reset(root: &PathBuf) {
    if root.exists() {
        fs::remove_dir_all(root).expect("reset fixture");
    }
    fs::create_dir_all(root.join("generated")).expect("create fixture");
    fs::create_dir_all(root.join("schema")).expect("create schema fixture");
    fs::write(root.join("schema/protocol.schema"), SCHEMA).expect("write schema");
}

fn fixture_root(name: &str) -> PathBuf {
    std::env::temp_dir().join(format!("zrail-generated-{name}-{}", std::process::id()))
}

fn contract() -> GeneratedSourceContract {
    GeneratedSourceContract {
        root: "generated".into(),
        manifest: "generated/MANIFEST.json".into(),
        inputs: vec!["schema/**".into()],
        target: 1_000,
        hard: 2_000,
        reason: "fixture compiler owns these files".into(),
        auxiliary: Vec::new(),
    }
}

fn entries(root: &std::path::Path, files: &[&str]) -> Vec<RepositoryEntry> {
    let mut entries = files
        .iter()
        .map(|file| RepositoryEntry {
            relative: format!("generated/{file}"),
            absolute: root.join("generated").join(file),
            kind: RepositoryEntryKind::File,
        })
        .collect::<Vec<_>>();
    entries.push(entry(root, "schema/protocol.schema"));
    entries
}

fn entry(root: &std::path::Path, relative: &str) -> RepositoryEntry {
    RepositoryEntry {
        relative: relative.into(),
        absolute: root.join(relative),
        kind: RepositoryEntryKind::File,
    }
}

fn manifest(files: &[(&str, &str)]) -> String {
    let files = files
        .iter()
        .map(|(path, source)| format!("{{\"path\":\"{path}\",\"sha256\":\"{}\"}}", digest(source)))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        concat!(
            "{{\"schema\":1,\"generator\":\"fixture 1\",",
            "\"inputs\":[{{\"path\":\"schema/protocol.schema\",\"sha256\":\"{}\"}}],",
            "\"files\":[{}]}}"
        ),
        digest(SCHEMA),
        files
    )
}
