#!/usr/bin/env bash
set -euo pipefail

repository_url=https://github.com/kafkars/kafka-driver

curl \
  --fail \
  --location \
  --output /dev/null \
  --show-error \
  --silent \
  --user-agent kafka-driver-release-qualification \
  "$repository_url"
